### PR TITLE
thumbnail

### LINKED ISSUE #75: Multiple sessions break thumbnails
Thumbnails do not show properly if more than one session with thumbnails enabled exists on the system.
The issue probably originates from the hard-coded variables for ueberzug (line 230-232).

### PR DESCRIPTION
**Pull request by Euro20179**
this should fix #75 but there is 1 issue that i noticed, when escaping out of fzf without selecting anything it will not remove the thumbnail directory because closing out of fzf closes out of ytfzf as well

### CODE REVIEW

**Comment by pystardust** [comment]
Also if you have 2 sessions open and you close one. The thumbs get deleted.

**Comment by Euro20179** [comment]
from my testing it works just fine after closing one of the sessions

**Comment by pystardust** [comment]
when the `save_before_exit` function is runs, the  thumbs are being removed, you might have exit the session before that.

**Comment by Euro20179** [comment]
it's possible, however each ytfzf instance gets it's own thumb_dir, so it shouldn't matter.

**Comment by pystardust** [comment]
@Euro20179 
I have merged this to a new branch multi-session and modified it. Now the thumbnails are being deleted. Even if a session is closed with sigkill, the next time the script runs it will delete the thumbs while leaving. 
- I have changed PPID to pid `$$`
- Stored pids in a pid file in cache dir
- using only on thumb dir
- added function delete_thumbnails, which will delete thumbnails if no other session is running.

**Comment by Euro20179** [comment]
nice

**Pull request closed without merging**
