### PR TITLE
Changable player

### LINKED ISSUE #50: Change player
Could an option to configure the video player be added? I am using [devour](https://github.com/salman-abedin/devour) to swallow the terminal window of mpv. So being able to do something like `ytfzf -p "devour mpv"` would be fantastic. Thanks!

### PR DESCRIPTION
**Pull request by westofer**
fix #50

### CODE REVIEW

**Comment by westofer** [comment]
dont merge, unstable

**Comment by pystardust** [comment]
letme know when its stable

**Comment by westofer** [comment]
dont want to risk buggy code

**Comment by ondrej256** [comment]
Thanks! I've just tried out `export YTFZF_PLAYER="devour mpv"` and it's showing `devour mpv not found. Please install it.`, although devour and mpv are both installed. Bug?

**Comment by westofer** [comment]
#58

**Comment by cybarspace** [comment]
> Thanks! I've just tried out `export YTFZF_PLAYER="devour mpv"` and it's showing `devour mpv not found. Please install it.`, although devour and mpv are both installed. Bug?

Sorry, that was my bad. I was trying to make mpv not be a hard dependency, but didn't think about when `YTFZF_PLAYER` has spaces. I made a [PR](https://github.com/pystardust/ytfzf/pull/60) reverting the change to `dep_ck`.

**Pull request merged**
