### PR TITLE
implements FZF_DEFAULT_OPTS

### LINKED ISSUE #54: FZF_DEFAULT_OPTS not being referenced
I like using the following in my default opts: `FZF_DEFAULT_OPTS="--bind=ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all"`, but I noticed they weren't taking when I added them to the script. `$FZF_DEFAULT_OPTS` needs to be referenced in the following functions:

```diff
format_menu () {
	if [ $is_ext_menu -eq 0 ]; then
		dep_ck "fzf"
++		prompt_menu='fzf -m --bind change:top --tabstop=1 --layout=reverse --delimiter="$(printf "\t")" --nth=1,2 $FZF_DEFAULT_OPTS'
--		prompt_menu='fzf -m --bind change:top --tabstop=1 --layout=reverse --delimiter="$(printf "\t")" --nth=1,2'
```

```diff
video_menu_img () {
	title_len=400
	format_awk | fzf -m --tabstop=1 --bind change:top --delimiter="$(printf "\t")" --nth=1,2 \
		--layout=reverse --preview "sh $0 -U {}" \
++        	--preview-window "left:50%:noborder:wrap" $FZF_DEFAULT_OPTS
--        	--preview-window "left:50%:noborder:wrap" $FZF_DEFAULT_OPTS
}
```

### PR DESCRIPTION
**Pull request by Euro20179**
fix #54

### CODE REVIEW

**Comment by pystardust** [comment]
Defaults args are taken by default.
The problem is some people have previews on in a different way in their default args. So i am clearning the default args in the start of the script

**Comment by pystardust** [comment]
We can add some sort of a choice for people who want their fzf defaults. What do you thing?

**Comment by Euro20179** [comment]
I think that there should be a way to have fzf defaults although idk how it could be implemented, this seems like a pretty simple way to do it.

**Comment by Euro20179** [comment]
I did some basic testing and unless you break fzf itself with the FZF_DEFAULT_OPTS it seems to work anyway (tested `--delimiter` `--tabstop` `--bind change --nth`), I could have tested them badly because i don't really know what I'm doing lol, but it seems to work

**Comment by Euro20179** [comment]
there's another option where there could be YTFZF_ENABLE_FZF_DEFAULT_OPTS or something (that variable name is kinda long) where when it's enabled fzf_default_opts works, it should be off by default.

**Comment by pystardust** [comment]
Initially I didn't clear the defaults, someone on reddit pointed out that thier defaults are really absurd for ytfzf. Thats why I thought of clearning them. But yes we can do that.

**Pull request merged**
