### PR TITLE
feat: shortcuts (credit to @simonhughcom (#288)) 

### PR DESCRIPTION
**Pull request by Euro20179**
shortcuts in fzf, finally

### CODE REVIEW

**Comment by simonhughcom** [comment]
All looks good, except for `disown` which is not posix, its not available is dash for example.
You can also use `nohup` which is posix compliant.

**Comment by Euro20179** [comment]
Thanks, fixed.

**Comment by pystardust** [comment]
Really nice implementation

consider the following refactors:

* Title may contain pipe
```diff
-       "$title_shortcut") printf "%s\n" "$selected_data" | cut -d '|' -f1; return 1 ;;
+       "$title_shortcut") printf "%s\n" "$selected_data" | cut -d "$tab_space" -f1; return 1 ;;
```
* unneeded sed
```diff
        #through this loop, the selected data which was truncated by formatting is retrived.
-       selected_key=$(printf "%s" "$selected_data" | sed 1q)
+       selected_key=${selected_data%%${new_line}*}
        selected_urls=
```
* formatting huge lines with breaks
```diff
-    IFS="," read -r urls_shortcut title_shortcut open_browser_shortcut watch_shortcut download_shortcut audio_shortcut search_shortcut << EOF
-$shortcuts
-EOF
-    case $selected_key in
+       IFS="," read -r \
+               urls_shortcut title_shortcut open_browser_shortcut watch_shortcut \
+               download_shortcut audio_shortcut search_shortcut <<-EOF
+       $shortcuts
+       EOF
```

**Comment by Euro20179** [comment]
Everything is good except the first one, the title shortcut for some reason only works with thumbnails, otherwise it displays the entire selection. which is why i split by pipe, but you are correct, so i'll look for another way.

**Comment by pystardust** [comment]
Ah yes, while running without thumbnails we are using the column command with out the output separator as its not posix. So we don't have the tab separation on the data. Maybe we could stick with the pipe for now

**Comment by Euro20179** [comment]
> Maybe we could stick with the pipe for now

I actually think this is a bad idea because a lot of videos have a pipe in them.

**Comment by pystardust** [comment]
we would need to grep the line out from the data using the surl , that would need an additional function. We can't do much with the raw fzf output

**Comment by Euro20179** [comment]
I have an idea, instead of seperating by tab, we could separate by the length of the titlle gap. I just don't know how to do that yet.

**Comment by pystardust** [comment]
I think the length is determined by the column command. We tried to manually set the length  using awk's printf, but that failed on emoji. So we stuck with `column`.
What if we suffix the title with `\t` in jq itself?

**Comment by Euro20179** [comment]
I tried this, I believe it doesn't work becase the gap size would be longer than than the actual gap size, because the title eats up more of the padding.
```sh
gap="$(printf "%-${title_len}.${title_len}s\t" "t" | sed 's/t//')"
```

**Comment by pystardust** [comment]
even if the title were small, this wouldn't work since column is using tabspaces as its separator

**Comment by Euro20179** [comment]
i actually tested this myself to be sure, a title on youtube can't have more than 1 space in it, I'm going to separate by 2 spaces using awk, because cut can't use more than 1 character as a separator. Im not positive about peertube but i doubt they allow more than 1 space.

**Comment by Euro20179** [comment]
ok, i've applied your changes.

**Comment by pystardust** [comment]
> i actually tested this myself to be sure, a title on youtube can't have more than 1 space in it, I'm going to separate by 2 spaces using awk, because cut can't use more than 1 character as a separator. Im not positive about peertube but i doubt they allow more than 1 space.

This feature won't be a really crucial feature as it outputs only the name of the video, so I think is fine

Seems good lets merge it. Maybe we can test it out and push to master

**Review by pystardust — APPROVED** [review]

**Pull request merged**
