### PR TITLE
fix: `sort` and `detach` options

### PR DESCRIPTION
**Pull request by Mudskipper875**
Also added the relevant options in the man page

### CODE REVIEW

**Comment by Euro20179** [comment]
previously you could do `--sort=1`, `--sort=0`, and `--sort`. The reason for this was if you had `is_sort=1` in your config you could disable it and vice versa. `--sort` is just a shorthand for `--sort=1`
I have a branch that addresses this for all the options. If you make this just about the manpage I'll merge it.

**Comment by Euro20179** [comment]
the diff is rather short, you could merge it into this branch.

```diff
diff --git a/ytfzf b/ytfzf
index e8c48c0..5b60334 100755
--- a/ytfzf
+++ b/ytfzf
@@ -727,28 +727,31 @@ player () {
 parse_opt () {
        opt=$1
        optarg=$2
+       #for some reason optarg may equal opt intentionally,
+       #this checks the unmodified optarg, which will only be equal if there is no = sign
+       [ "$opt" = "$OPTARG" ] && optarg=""
        case $opt in
                h|help) usage; exit ;;
-               D|external-menu) is_ext_menu=1 ;;
-               m|audio-only) is_audio_only=1 ;;
-               d|download) is_download=1 ;;
+               D|external-menu) is_ext_menu=${optarg:-1} ;;
+               m|audio-only) is_audio_only=${optarg:-1} ;;
+               d|download) is_download=${optarg:-1} ;;
                f|formats) : ;; # TODO
                H|history) : ;; # TODO
                x|history-clear) : ;; # TODO
                q|search-history) : ;; # TODO
-               a|auto-select) is_interface_scripting=1; is_auto_select=1 ;;
-               A|select-all) is_interface_scripting=1; is_auto_select=1; scripting_video_count=100 ;;
-               r|random-select) is_interface_scripting=1;is_random_select=1 ;; 
+               a|auto-select) is_interface_scripting=${optarg:-1}; is_auto_select=${optarg:-1} ;;
+               A|select-all) is_interface_scripting=${optarg:-1}; is_auto_select=${optarg:-1}; scripting_video_count=100 ;;
+               r|random-select) is_interface_scripting=${optarg:-1};is_random_select=${optarg:-1} ;; 
                n|link-count) scripting_video_count=$optarg;; 
-               t|show-thumbnails) show_thumbnails=1 ;;
+               t|show-thumbnails) show_thumbnails=${optarg:-1} ;;
                v) printf 'ytfzf: %s \n' "$YTFZF_VERSION"; exit;;
                L) info_to_print="$info_to_print,L" ;;
                c) scrape=$optarg ;;
                I) info_to_print=$optarg ;;
                #long-opt exclusives
-               is-sort) is_sort=$optarg ;;
+               is-sort) is_sort=${optarg:-1} ;;
                video-pref) video_pref=$optarg ;;
-               is-detach) is_detach=$optarg ;;
+               is-detach) is_detach=${optarg:-1} ;;
        esac
 }
 
@@ -768,7 +771,7 @@ while getopts "han:dmfc:tI:LTD${long_opt_char}:U" OPT; do
                        ;;
                "$long_opt_char")
                        parse_opt "${OPTARG%%=*}" "${OPTARG#*=}" ;;
-                       *)
+               *)
                        parse_opt "${OPT}" "${OPTARG}" ;;
        esac
 done
```

**Comment by Mudskipper875** [comment]
I've turned on 'allow edits by maintainer'

**Comment by Euro20179** [comment]
wow, that actually worked, i've never tried this before lol.

**Comment by Mudskipper875** [comment]
>```
>is-sort) is_sort=${optarg:-1} ;;
>is-detach) is_detach=$optarg ;;
>```

But this would mean the command line options will now be `--is-sort` and `--is-detach` right?

**Comment by Euro20179** [comment]
> But this would mean the command line options will now be --is-sort and --is-detach right?

it can either be `--is-sort` or `--is-sort=1`

**Comment by Mudskipper875** [comment]
> > ```
> > sort) is_sort=${optarg:-1} ;;
> > detach) is_detach=$optarg ;;
> > ```

Wouldn't this achieve the same result, but with a shorter command line option?

**Comment by Euro20179** [comment]
yes, but shorter command line options are easier to type

**Comment by Mudskipper875** [comment]
> yes, but shorter command line options are easier to type
> 
> edit:
> ohhh, you're saying we should change it to `--sort` ? if so i agree, i was going to do that in a separate pr though.

Oh okay then 👍

**Comment by Euro20179** [comment]
you put --sort and --detach in the manpage, i'll just do it now.

**Pull request merged**
