### PR TITLE
Use tmpfs for speed and I/O reduction

### PR DESCRIPTION
**Pull request by futureisfoss**

### CODE REVIEW

**Comment by futureisfoss** [comment]
Sorry I didn't notice the development branch, I'm still kinda new to github.

**Comment by Euro20179** [comment]
> Did I fix it? Or do I have to create a new PR for the development branch?

Quite honestly I didn't even know that you didn't have to reopen a pr to change the branch. But yes you did fix it.

I probably will not be merging this for a little bit, as I would like to get v2.5.3 out before adding more to the development branch. (I also need to test it)

**Comment by futureisfoss** [comment]
> Quite honestly I didn't even know that you didn't have to reopen a pr to change the branch.

I tried clicking the edit button and it allowed me to change the base branch, I was also surprised at first. One side effect of this was that it also added https://github.com/pystardust/ytfzf/pull/610/commits/046b6b0eae0ba4b0c71040b58da5fb8ccd7da33b to my PR.

> I probably will not be merging this for a little bit, as I would like to get v2.5.3 out before adding more to the development branch. (I also need to test it)

Yeah sure :)

**Comment by Euro20179** [comment]
> I tried clicking the edit button and it allowed me to change the base branch

Good to know.

**Comment by Euro20179** [comment]
I made some changes to account for submenus. submenu's cache dir should be in it's parents cache dir, which wasn't working, but i fixed it.

**Pull request merged**
