### PR TITLE
feat: more ways to view thumbnails

### PR DESCRIPTION
**Pull request by Euro20179**
addresses #44

### CODE REVIEW

**Comment by piotryordanov** [comment]
Can it be made to support `w3m`?

**Comment by Euro20179** [comment]
It would be nice to be able to support w3m, however we have not found a way to get w3m to work with fzf

**Comment by piotryordanov** [comment]
Oh okay. So, is chaca the only alternative option for wayland?

**Comment by Euro20179** [comment]
currently yes, sadly, so far the only things that work are programs that print ascii characters and color them.

**Comment by piotryordanov** [comment]
THank you for answering.
So, is that an fzf limitation? Or, a limitation of FZF running in Wayland?

**Comment by Euro20179** [comment]
To my knowledge it's either a limitation of fzf or curses (the library that fzf uses)

**Pull request merged**
