### PR TITLE
New features: store and show view dates, allow clearing partial history

### PR DESCRIPTION
**Pull request by ido50**
This pull request introduces two features, in two separate commits. There are detailed explanations in each commit message, but in short, the features are:

1. Store view dates in history, show when `-H` is used.
2. Allow removing videos from history that were viewed before the provided date or interval (e.g. '2 days ago') via new option `--clear-before`.

It is my hope that you will at least find the first feature useful for common users. The second feature requires the first, but I'm not sure you'll find it useful enough to include. Personally, I'd like to automate clearing of history (e.g. via a cron job), but still keep a certain amount of recent history. If you feel only the first feature should enter, I'll gladly open a PR purely for it.

These are backwards compatible changes, and I have taken care to make sure all changes are POSIX-compatible. That said, it's entirely possible that I missed something in my tests. Please read the note in the first commit message about terminal widths and let me know if any changes are necessary.

Thanks!

### CODE REVIEW

**Comment by pystardust** [comment]
Nice implementation, but please pull requests on the development branch. We don't push directly to master.

**Comment by pystardust** [comment]
As you mentioned regarding cronjobs. One could trim the top of the history file and make sure the history file has max n lines. 
 Also let us try thinking different ways to store view date. Since currently short url is being pushed to the right, and so will every field after it. Maybe we could make a different format function specific to history.

**Comment by ido50** [comment]
I put the view date on the far right, so no existing column is pushed, unless I've mistaken your meaning. I started by putting it on the far left (i.e. the first column), but that would have broken backwards compatibility.

With regards to trimming by number of lines, that's actually what I'm doing now, but it's not really what I want. Heavy view days quickly destroy recent activity. I like having a set amount of time to go back to videos I watched.

Let me know how to proceed. Of course I'll re-open the PR on top of the development branch as necessary.

**Comment by pystardust** [comment]
What if we replace the upload date of the video with the date viewed?
Cause the upload date is relative, and having it in the history makes it not very usefull. Implementing it this way would also make it such that the user can see those dates.

**Comment by ido50** [comment]
I could do that. Ideally history would have both in absolute dates, but if the upload date is relative it is indeed not useful in the history. Should I re-implement like this?

**Comment by pystardust** [comment]
Unfortunately, there doesn't seem to be any absolute date in the search result page. Yeah this was seems better

**Pull request closed without merging**
