### PR TITLE
Add flag to use ytfzf as yt-search

### PR DESCRIPTION
**Pull request by JojiiOfficial**
Added a new flag `-L` to use ytfzf as search tool, the youtube URL of the selected link will be printed out to stdout. I didn't go through all of the code so I may have missed something.

Edit: This doesn't work together with downloading thumbnails.

### CODE REVIEW

**Comment by JojiiOfficial** [comment]
Should work now

**Comment by pystardust** [comment]
@JojiiOfficial instead of the last commit. Make thumbnail flag=0 in the start itself. That would be much cleaner what do you thing?

**Comment by JojiiOfficial** [comment]
Yep you're right!

**Comment by JojiiOfficial** [comment]
Nvm, then you don't see the thumbnails when you select the video

**Comment by pystardust** [comment]
Hey, I just understood what you meant in the first solution. 
But there is one more problem. There will be "." comming from download meter we will need to account for that also. I am currently occupied, Ill get to it in a half a day.

**Comment by JojiiOfficial** [comment]
No hurries. There are (should be) no more '.' coming from the thumbnail download meter.

**Comment by pystardust** [comment]
Let, us do it in a way, such that both the thumbails and urls work together. Lets rework that part comletely ig. One option could to be to completely remove the dots and the downloading thumbs that is being printed.

**Comment by JojiiOfficial** [comment]
That is exactly the way how it's working right now :)
Look at [this part](https://github.com/pystardust/ytfzf/pull/33/files#diff-a2ab70d1ccc85ac09c9540a95a34bb5fbe9a25b67ab7a2cc98ba5329b4391396R148-R163)

**Comment by JojiiOfficial** [comment]
I (hopefully) fixed it. Generally a `-q` (quiet) option would be nice. This could be set automatically on `-L` to prevent the output.

**Comment by pystardust** [comment]
@JojiiOfficial Nice work. Im merging this. Ill clean the if statemets into one liners using &&'s 
btw its posix not bash :laughing:

**Pull request merged**
