### PR TITLE
Solve issues with audio-only playback

### PR DESCRIPTION
**Pull request by qoheniac**
See https://github.com/pystardust/ytfzf/issues/203

### CODE REVIEW

**Comment by pystardust** [comment]
`--no-video` disables video playback. But if we choose a format with video, won't youtube-dl buffer the video too?

**Comment by pystardust** [comment]
Opps, I just read the manual you quoted, it doesnt download the video

**Comment by qoheniac** [comment]
No problem, I think I wrote that edit just the moment when you wrote your comment here.

**Comment by pystardust** [comment]
Nice, this would work for mpv. It might be an issue for external players likes vlc
We would need to take care of them too

**Comment by pystardust** [comment]
Send the PR to development we could merge and work on it there

**Comment by qoheniac** [comment]
Here you go: https://github.com/pystardust/ytfzf/pull/206

**Comment by qoheniac** [comment]
> It might be an issue for external players likes vlc

I wanted to look into this but how do I even use other players? If I simply try `YTFZF_PLAYER=vlc ytfzf something` with version 1.1.2 and pick some video I always get this error message: `http stream error: local stream 1 error: Cancellation (0x8)`.

**Pull request closed without merging**
