### PR TITLE
Add option for getting channel feed URL

### PR DESCRIPTION
**Pull request by txgk**
It is quite annoying to search channel id in the page source for getting feed URL. Why not use my favorite youtube script for this?

### CODE REVIEW

**Comment by Euro20179** [comment]
There's already an option called `--channel-url` that you can use to get the "real" link to a channel (which includes the id), so this feels a bit unnecessary, especially considering how specific it is.

If you added the below to `~/.config/ytfzf/conf.sh` you can use `ytfzf --feed="a-url-to-a-channel"`

```sh
on_opt_parse_feed (){
    link=$(_get_real_channel_link "$optarg")
    echo "https://www.youtube.com/feeds/videos.xml?channel_id=${link##*/}"
    exit 0
}
```

I believe that if this function supported multiple sites, eg: reddit, it would be a lot more useful. However I think that either way, having it in the main script is a bit excessive, and works better as an extension (I'll try to write it)

Also please base your changes on the development branch.

**Comment by Euro20179** [comment]
I have created a scraper that does pretty much what this does.

Here is the link to the file: https://github.com/pystardust/ytfzf/blob/development/addons/scrapers/feed-url

It's basically just an improved version of what this is.

You can do `ytfzf -c feed-url youtube/pewdiepie r/linux` and it will give you the rss feeds for pewdiepie's channel, and r/linux, in addition it sends a ping to the rss links to make sure they exist.

**Comment by txgk** [comment]
Thank you, this is pretty useful. But the flaw is that `_get_real_channel_link` function is not error resistant - it returns gibberish for invalid channels and fails when youtube link doesn't have `www` prefixed.

**Comment by Euro20179** [comment]
>  it returns gibberish for invalid channels

Shouldn't be too hard to fix

> And fails when youtube link doesn't have www prefixed

Again shouldn't be too hard.

However we'll just have to see, and feel free to give fixing these a shot

**Pull request closed without merging**
